export COMPALGOCLAW_OPENALEX_EMAIL="ypf2944164500@gmail.com"
export COMPALGOCLAW_NCBI_EMAIL="ypf2944164500@gmail.com"
export COMPALGOCLAW_ENABLE_SCIHUB=1
export COMPALGOCLAW_SCIHUB_MIRRORS="https://sci-hub.ee"
